services:

  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "DbNginx"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php_container
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # É uma boa prática nomear o arquivo de configuração, ex: default.conf
      - ./conf/nginx/default.conf:/etc/nginx/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
    labels:
      - "com.meuprojeto.purpose=mysql_data_persistence"

networks:
  app-network:
    driver: bridge
